---
# A basic set of tools to install on an ubuntu box
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo

  tasks:
    - name: apt update cache
      apt: update_cache=yes

    - name: apt update
      apt: upgrade=dist

    - name: Install list of packages
      apt: name={{item}} state=present
      with_items:
        - git
        - unzip
        - curl
        - bash-completion
        - tree
        - ntp
        - bc
        - python-pip

    - name: pip packages
      pip:
        name: awscli
