---
# A basic set of tools to install on an ubuntu box
- hosts: localhost
  connection: local
  sudo: yes
  tasks:
  - name: apt update
    apt: update_cache=yes

  — name: apt update
    command: sudo apt-get update

  — name: Install list of packages
    apt: name={{item}} state=installed
    with_items:
      - git
      — unzip
      — curl
      — bash-completion
      — tree
      — ntp
      - bc

  - name: pip packages
    pip:
      name: awscli
-
