---
# A basic set of tools to install on an ubuntu box
# I'll eventually make this work with ansible's facts to switch between OS families
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo

  tasks:
    - name: apt update cache
      apt: update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: apt update
      apt: upgrade=dist
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install list of packages
      apt: name={{item}} state=present
      with_items:
        - git
        - unzip
        - curl
        - bash-completion
        - tree
        - ntp
        - bc
        - jq
        - python-pip
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: pip packages
      pip:
        name: awscli
